language: php

sudo: required

php:
  - 5.3.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

env:
  PREFER_LOWEST=""

matrix:
  fast_finish: true
  include:
    - php: 5.3.3
      env: PREFER_LOWEST="--prefer-lowest"

before_script:
  - sudo apt-get install bsdtar zip
  - npm install connect serve-static
  - composer update --prefer-source --no-interaction $PREFER_LOWEST
  - if [ -n "$PREFER_LOWEST" ];then composer update phpunit/phpunit --prefer-source --no-interaction --with-dependencies;fi
  
script:
  - make test
  - >
      if [ $(phpenv version-name | tr '[:upper:]' '[:lower:]') != 'hhvm' ];
        then make scrutinizer;
      fi
